### ISSUE TITLE
Shift + Left Click during gameplay presses C

### ISSUE THREAD

**Issue by LiamShinkso** [C1rdec/Poe-Lurker#253] opened 2021-04-19 11:24 UTC
During gameplay (no trades) I hit Shift which I have bound to my Quicksilver flask and because I'm hold LMB to move it opens my inventory which I have bound to C. Only happens when Lurker is running. Not entirely sure which shortcut is doing it?

**Comment by kwanrong** [comment] 2021-04-19 16:27
I have the same issue. (v1.9.3)
My C key binds to inventory, every time I tend to unstack something with Shift+LeftClick and it will presses C and closes my inventory.

**Comment by kwanrong** [comment] 2021-04-19 17:25
I have the same issue (v1.9.3)
Every time I tend to unstack currency or something with Shift+LeftClick, C key will be pressed.

**Comment by C1rdec** [comment] 2021-04-20 14:15
This issue is fixed in dev basically Shift + Click trigger a copy (Ctrl + C).

**Comment by C1rdec** [comment] 2021-04-20 14:16
Duplicate of #252

**Closed by C1rdec** 2021-04-20 14:16 UTC
