### ISSUE TITLE
Typed commands into the game are prepended with 'a'

### ISSUE THREAD

**Issue by Slowbad** [C1rdec/Poe-Lurker#206] opened 2020-09-25 22:59 UTC
I'm using version 1.7.5 and I'm getting the same problem as  #140 where copied text gets prepended with an 'a'. What's in the clipboard seems to be fine, just the resulting message sent to PoE. I started using this at the beginning of the league and didn't have any issues until a few days ago after a restart. I've had to turn off the program for now to avoid whispering everyone with all these commands.

![2020-09-25 18_27_16-Window](https://user-images.githubusercontent.com/361420/94322645-0b9d7300-ff61-11ea-80b8-d4c1201dfe94.png)

**Comment by C1rdec** [comment] 2020-09-29 15:48
Are you experiencing this issue only with outgoing trade?

**Comment by C1rdec** [comment] 2020-09-30 02:41
I'm not able to reproduce the bug... I created an application that I can trigger the Outgoing trade very fast and every single trade is going trough...

**Comment by C1rdec** [comment] 2020-10-01 05:34
Fixed in 1.7.6.

**Closed by C1rdec** 2020-10-01 05:34 UTC
