### ISSUE TITLE
Red Corner Does Nothing?

### ISSUE THREAD

**Issue by WhiteSammy** [C1rdec/Poe-Lurker#53] opened 2020-01-26 06:32 UTC
I thought it was supposed do send the deny message for item sold but it appears to just close the notification box. Everything else seems to work fine.

[https://i.gyazo.com/860b7a981be683486002de133c6852df.mp4](url)

EDIT: Also, I see that there is a field for the "Still Interested" but how would one trigger that text?

EDIT2: Okay Ctrl+Click sends Sold message.

EDIT3: Can the red corner do 'sold' instead and ctrl+click send the 'still interested?'

EDIT4: Okay interesting thing. I tried to see what would happen if you ctrl+click'd after you get the the trade step and now the box for searching for an item won't go away. Resending the message and hitting the red corner doesn't eliminate it, ctrl+click doesn't remove it, and trading a new item to completion doesn't get rid of it either.

**Comment by C1rdec** [comment] 2020-01-26 21:23
There's no "Deny message" the red corner will just dismiss the Offer.

For still interested you can trigger by Ctrl + Shift an Offer. (I'm working on an User Guide) 

And for your last edit I dont understand.

**Comment by WhiteSammy** [comment] 2020-01-26 21:32
[https://i.gyazo.com/891e051adc16c20b877514ef0f08e540.mp4](url)

In regards to the last edit.

**Comment by C1rdec** [comment] 2020-01-26 21:44
Mmm will take a look into that

**Comment by C1rdec** [comment] 2020-01-26 23:36
Are you able to reproduce the issue?

**Comment by WhiteSammy** [comment] 2020-01-27 01:46
I can't seem to recreate it atm but I know it happened when I got it to the trade stage and then ctrl+clicked to close.  I'll let you know if it happens again

**Comment by C1rdec** [comment] 2020-02-04 14:59
Any updates?

**Comment by C1rdec** [comment] 2020-02-10 16:36
I'll close this issue for now since no update is provided.

**Closed by C1rdec** 2020-02-10 16:36 UTC

**Comment by WhiteSammy** [comment] 2020-02-11 01:40
Yeah, I haven't been able to reproduce the bug.
