### ISSUE TITLE
Toggle for Outgoing Offer Overlay

### ISSUE THREAD

**Issue by ulquiomaru** [C1rdec/Poe-Lurker#182] opened 2020-07-02 09:36 UTC
It's frustrating when I whisper someone with an offer and alt tab to another window, but the outgoing offer counting down to 0 triggers a switch back to the PoE window.

I assume the cause is redrawing/hiding the outgoing offer overlay.

A toggle for this behavior and/or the outgoing offer overlay should be easy enough to implement and solve this issue.

**Comment by C1rdec** [comment] 2020-07-02 12:53
If the offers would stay this UI would become a mess quickly. Ade you saying that the timer is to short for you?

**Comment by ulquiomaru** [comment] 2020-07-02 19:44
I'm saying that I don't want any outgoing trade offers to show up.  I don't use that feature at all, and it is bugged right now:
when the offer times out it alt tabs back to the client while I'm busy working on another window.

**Comment by ulquiomaru** [comment] 2020-07-02 19:51
![image](https://user-images.githubusercontent.com/1519725/86403512-88001d00-bcb6-11ea-84f6-faa07d123768.png)
commit: b41f27884238fc707702915ffa1da60b4be9795a

I have a problem with this commit.  Can you revert and make it optional?

**Comment by C1rdec** [comment] 2020-07-02 20:55
The problem is fixed in dev.

**Closed** 2020-07-02 20:56 UTC
