### ISSUE TITLE
Item description tag in wrong position?

### ISSUE THREAD

**Issue by vhbert** [C1rdec/Poe-Lurker#7] opened 2020-01-04 09:03 UTC
The new tag which shows the name of the item being sold is positioned wrong it seems.
Playing on 3440x1440 Resolution, so this might have something to do with it.
I've attached a screenshot to show the location of the item name. (Center bottom)

![image](https://user-images.githubusercontent.com/5436436/75260722-08b68600-57b8-11ea-9646-dc9d7e534ba9.png)

**Comment by C1rdec** [comment] 2020-01-04 16:17
Yeah there is an issue with 4k I'll close the issue an open a new one related to 4k

**Comment by C1rdec** [comment] 2020-01-04 16:22
Duplicate of #9

**Comment by C1rdec** [comment] 2020-01-06 02:47
This is due to wpf Popup [screen edge clipping](https://stackoverflow.com/questions/4632316/is-there-any-way-to-stop-a-wpf-popup-from-repositioning-itself-when-it-goes-off).

**Comment by C1rdec** [comment] 2020-01-14 16:24
Can you see if 1.2.4 fixed your issue

**Comment by vhbert** [comment] 2020-01-14 18:19
Sadly it did not.

**Comment by C1rdec** [comment] 2020-01-14 18:20
I get it fixed 🤛

**Comment by C1rdec** [comment] 2020-02-25 14:30
I'll move the Position over the LifeBulb. 
I tried to fix this issue with no success... The main problem is that I use a WPF Popup and by default when the Popup detect Screen Clipping (that is very sensitive) the position is reversed...

**Comment by C1rdec** [comment] 2020-02-27 01:39
Fixed in 1.4.8

**Closed by C1rdec** 2020-02-27 01:39 UTC
Labels: bug
