### ISSUE TITLE
Nothing happens.

### ISSUE THREAD

**Issue by JamesASW** [C1rdec/Poe-Lurker#112] opened 2020-04-09 05:41 UTC
Poelurker is running, nut doesn't not show anything.

I did find the log which contains an error message:
[2020-04-09.log](https://github.com/C1rdec/Poe-Lurker/files/4454225/2020-04-09.log)

**Comment by thatguy692** [comment] 2020-04-09 11:51
same problem here, just launched the app noting happened, launched it again and got "another instance is running" message.
Can't find the running process though..

**Comment by C1rdec** [comment] 2020-04-09 13:32
@JamesASW I will need to connect with you on Discord
@thatguy692 Can you provide your log

**Comment by C1rdec** [comment] 2020-04-09 14:35
Discord: https://discord.gg/jYujrJ 

My username is **Cedrico**

**Comment by C1rdec** [comment] 2020-04-11 14:15
I'll close this issue since the issue is to broad and no information is provided.

**Closed by C1rdec** 2020-04-11 14:15 UTC
