### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by Madlib7** [C1rdec/Poe-Lurker#230] opened 2021-01-15 17:49 UTC
[SquirrelSetup.log](https://github.com/C1rdec/Poe-Lurker/files/5822145/SquirrelSetup.log)
I get an error when I try to install. I've tried removing the program and deleting the folder in appdata and trying again, but no luck.

**Comment by C1rdec** [comment] 2021-01-15 17:54
Can you join the discord so we can connect?

**Comment by C1rdec** [comment] 2021-01-15 17:56
Could not find a part of the path 'C:\Users\IceBox\AppData\Local\PoeLurker\packages\RELEASES'

**Comment by C1rdec** [comment] 2021-01-16 07:39
This issue seems to be related to Windows N

**Comment by C1rdec** [comment] 2021-01-19 04:48
Not able to reproduce I will close this for now since we dont have enough information.

**Closed by C1rdec** 2021-01-19 04:48 UTC
